### ISSUE TITLE
Decouple Redis from the emitter

### ISSUE THREAD

**Issue by Maxwell2022** [rase-/socket.io-php-emitter#4] opened 2014-06-01 10:06 UTC
I've forked your project and I'll try to decouple Redis from the emitter.
I personally won't use redis to send events to nodejs server.

I'll let you know how I go but I'll probably start from scratch :)

**Comment by rase-** [comment] 2014-06-01 10:11
Hi @Maxwell2022! What are you thinking of using instead of redis? The emitter uses redis so that it can communicate with the [redis adapter](https://github.com/Automattic/socket.io-redis).

**Comment by Maxwell2022** [comment] 2014-06-01 10:27
I'm not sure yet. I need to send events to nodejs server with a simple array of data (JSON string) but I don't need Redis to do that. I'm looking into native PHP socket to send message to nodejs server instead of PECL `msgpack_pack`. I'm not sure I'm going into the right direction yet, just investigating building a test suite.

**Comment by Maxwell2022** [comment] 2014-06-01 10:31
Reading about the **redis adapter** I'm not sure I understand what this library is doing anymore. I thought it was a simple PHP script that could emits events to socketio specifying a data argument.

**Comment by rase-** [comment] 2014-06-01 10:34
@Maxwell2022 the idea is that you can emit events without having to change any code on the Node.js server at all, when you are using the redis adapter. It is for a similar purpose than what you suggested of doing, but not quite the same idea. :)

**Comment by rase-** [comment] 2014-06-01 10:35
The redis adapter is useful for any multi-process setup. So with this adapter (and the original Node.js implementation) you can hook into that multi-process setup and emit events from a non-socket.io process without changing anything. :)

**Comment by rase-** [comment] 2014-06-01 10:37
@Maxwell2022 the idea you described sounds good too. I suggest you start from scratch and also write a Node module that will enable you to easily attach your implementation to socket.io.

**Comment by rase-** [comment] 2014-06-01 10:40
@Maxwell2022 I will close this issue just because it's something I won't be able to address here, since I want this module to work with the redis adapter. We can continue to talk about the idea here even if the issue is closed, though. :)

**Closed as completed by rase-** 2014-06-01 10:40 UTC

**Comment by Maxwell2022** [comment] 2014-06-01 10:47
sure, not sure what I'm getting into at the moment. I though socket.io was simply listening to a specific port and so you could send event opening a simple socket from PHP and writting into it.

**Comment by rase-** [comment] 2014-06-01 10:50
@Maxwell2022 right. Actually it's the redis adapter that is listening to events by redis subscribe. You would need to make the receiving socket yourself to be enable to emit through a simple socket connection.

**Comment by rase-** [comment] 2014-06-01 11:34
@Maxwell2022 there's also other options here, worth considering for your particular situation: https://packagist.org/search/?q=Socket.io
